
networks:
  demo:
services:
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres-pgvector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgvector_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data17
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - demo
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - demo
    depends_on:
      - postgres
volumes:
  postgres_data:
